#!/bin/bash

echo "🔧 Konfigurasi Router/Proxy untuk Forward Real IP"
echo ""
echo "Server IPTV sekarang sudah siap menerima Real IP dari client yang berada di VLAN berbeda."
echo ""
echo "====================================================================================="
echo "UNTUK ROUTER/PROXY yang menforward ke server ini, tambahkan konfigurasi berikut:"
echo "====================================================================================="
echo ""
echo "▶️ NGINX (Reverse Proxy):"
echo "----------------------------"
echo "location / {"
echo "    proxy_pass http://172.23.96.130:3000;"
echo "    proxy_set_header X-Real-IP \$remote_addr;"
echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "    proxy_set_header Host \$host;"
echo "}"
echo ""
echo "▶️ Apache (Reverse Proxy):"
echo "----------------------------"
echo "ProxyPass / http://172.23.96.130:3000/"
echo "ProxyPassReverse / http://172.23.96.130:3000/"
echo "ProxyPreserveHost On"
echo "RequestHeader set X-Real-IP %{REMOTE_ADDR}s"
echo "RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s"
echo ""
echo "▶️ HAProxy:"
echo "----------------------------"
echo "frontend iptv_frontend"
echo "    bind *:80"
echo "    option forwardfor"
echo "    http-request set-header X-Real-IP %[src]"
echo "    default_backend iptv_backend"
echo ""
echo "backend iptv_backend"
echo "    server iptv1 172.23.96.130:3000"
echo ""
echo "▶️ MikroTik Router:"
echo "----------------------------"
echo "/ip firewall nat"
echo "add action=dst-nat chain=dstnat dst-port=3000 protocol=tcp to-addresses=172.23.96.130"
echo ""
echo "# Untuk preserve source IP, gunakan srcnat bypass:"
echo "add action=accept chain=srcnat dst-address=172.23.96.130 dst-port=3000"
echo ""
echo "====================================================================================="
echo "INFORMASI JARINGAN:"
echo "====================================================================================="
echo "Server IPTV IP: 172.23.96.130:3000"
echo "VLAN Client 1: 192.168.112.0/24"
echo "VLAN Client 2: 172.16.88.0/24"
echo ""
echo "Server akan detect IP dari header berikut (berurutan):"
echo "  1. X-Forwarded-For (prioritas pertama)"
echo "  2. X-Real-IP (jika tidak ada X-Forwarded-For)"
echo "  3. Connection IP (fallback)"
echo ""
echo "====================================================================================="
echo "TESTING:"
echo "====================================================================================="
echo "Dari client di VLAN 192.168.112.0/24 atau 172.16.88.0/24, akses:"
echo "  http://<router-ip>:3000/playlist.m3u8?token=default123"
echo ""
echo "Cek log server untuk melihat Real IP yang terdeteksi:"
echo "  tail -f /home/dindin/iptv-server/server.log"
echo ""
echo "Log akan menampilkan: 🔍 Real IP from X-Forwarded-For: 192.168.112.x"
echo "====================================================================================="
