#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         IPTV Server - Perbaikan untuk Linux Server          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ PERUBAHAN YANG SUDAH DILAKUKAN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Trust Proxy Configuration"
echo "   ❌ Sebelum: trust proxy: true (terlalu permissive)"
echo "   ✅ Sesudah: Specific untuk private networks"
echo "              ['loopback', '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']"
echo ""
echo "2️⃣  IP Detection Logging"
echo "   ❌ Sebelum: Logging selalu aktif → spam log"
echo "   ✅ Sesudah: Hanya log jika DEBUG_IP=true"
echo ""
echo "3️⃣  Environment Configuration"
echo "   ✅ File .env untuk konfigurasi production"
echo "   ✅ .env.example sebagai template"
echo ""
echo "4️⃣  Stream Stability"
echo "   ✅ AUTO_STOP_DELAY: 300s (5 menit)"
echo "   ✅ CLIENT_TIMEOUT: 90s (3x playlist refresh)"
echo "   ✅ CLEANUP_INTERVAL: 30s"
echo ""
echo "5️⃣  Scripts & Documentation"
echo "   ✅ setup-linux-server.sh - Auto setup untuk Linux"
echo "   ✅ TROUBLESHOOTING.md - Panduan lengkap troubleshooting"
echo "   ✅ WSL-vs-LINUX.md - Perbandingan WSL vs Linux Server"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 CARA DEPLOY KE LINUX SERVER:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# 1. Setup environment"
echo "   ./setup-linux-server.sh"
echo ""
echo "# 2. Edit konfigurasi (optional)"
echo "   nano .env"
echo ""
echo "# 3. Test run"
echo "   npm start"
echo ""
echo "# 4. Install sebagai systemd service"
echo "   ./install-service.sh"
echo ""
echo "# 5. Manage service"
echo "   sudo systemctl start iptv-server"
echo "   sudo systemctl status iptv-server"
echo "   sudo systemctl enable iptv-server"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 TROUBLESHOOTING:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Masalah IP Detection:"
echo "  1. Enable debug: echo 'DEBUG_IP=true' >> .env"
echo "  2. Restart: sudo systemctl restart iptv-server"
echo "  3. Watch logs: sudo journalctl -u iptv-server -f"
echo ""
echo "Masalah Firewall:"
echo "  Ubuntu: sudo ufw allow 3000/tcp"
echo "  CentOS: sudo firewall-cmd --permanent --add-port=3000/tcp"
echo ""
echo "Masalah Stream Restart Loop:"
echo "  - Tingkatkan timeout di .env"
echo "  - AUTO_STOP_DELAY=300000"
echo "  - CLIENT_TIMEOUT=90000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOKUMENTASI:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📄 TROUBLESHOOTING.md   - Panduan troubleshooting lengkap"
echo "  📄 WSL-vs-LINUX.md      - Perbedaan WSL vs Linux Server"
echo "  📄 router-config-guide.sh - Konfigurasi router/proxy"
echo "  📄 .env.example         - Template environment variables"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 AKSES SERVER:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "  Admin Panel:"
echo "    http://$SERVER_IP:3000/admin"
echo ""
echo "  Playlist (VLC):"
echo "    http://$SERVER_IP:3000/playlist.m3u8?token=default123"
echo ""
echo "  API Stats:"
echo "    http://$SERVER_IP:3000/api/stats/comprehensive"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
